[project]
name = "ftmsant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bleak>=2.1.1",
    "openant>=1.3.4",
    "loguru>=0.7.2",
    "pycycling>=0.4.1",
]
